name: test-build-validate
on:
  pull_request:
  push:
    branches:
      - main
      - staging-**
jobs:
  build-unminified-site:
    runs-on: ubuntu-20.04
    steps:
      - name: "Build Site with Hugo and Audit"
        uses: danielfdickinson/hugo-action-build-audit@main
        with:
          upload-html-validate-config: true
          upload-npm-json: true
          upload-site-as: unminified-site
          use-lfs: false
  validate-unminified-html:
    needs: build-unminified-site
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run hugo-action-html-validate
        uses: ./
